# Generated by Django 5.2.5 on 2025-08-27 10:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('pasteur', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EtatBesoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('designation', models.CharField(default='Aucune désignation', max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.CharField(max_length=100)),
                ('motif', models.TextField()),
                ('date_etat_besoin', models.DateField(auto_now_add=True)),
                ('validation_pasteur', models.BooleanField(default=False)),
                ('validation_caisse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe_Offrandes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_ordre', models.CharField(max_length=100)),
                ('description_recette', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe_Previsions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_ordre', models.CharField(max_length=100)),
                ('description_prevision', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='Api_prosphora_App.church')),
            ],
        ),
        migrations.CreateModel(
            name='Prevoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_compte', models.BigIntegerField()),
                ('nom_prevision', models.TextField(max_length=50)),
                ('montant_prevus', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annee_prevus', models.IntegerField()),
                ('descript_prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_prosphora_App.groupe_previsions')),
            ],
        ),
        migrations.CreateModel(
            name='Sorte_Offrande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_compte', models.CharField(max_length=20)),
                ('nom_offrande', models.TextField(max_length=50)),
                ('descript_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_prosphora_App.groupe_offrandes')),
            ],
        ),
        migrations.CreateModel(
            name='Payement_Offrande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departement', models.CharField(max_length=100)),
                ('type_payement', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_lettre', models.CharField(max_length=255)),
                ('type_monaie', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=255)),
                ('date_payement', models.DateField()),
                ('annee', models.IntegerField()),
                ('nom_offrande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_prosphora_App.sorte_offrande')),
            ],
        ),
        migrations.CreateModel(
            name='Ahadi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_postnom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_lettre', models.CharField(max_length=255)),
                ('motif', models.CharField(max_length=255)),
                ('date_ahadi', models.DateField()),
                ('annee', models.IntegerField()),
                ('nom_offrande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_prosphora_App.sorte_offrande')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('membre', 'Membre')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Api_prosphora_App.church')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='groupe_offrandes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
