# Generated by Django 4.2.16 on 2025-08-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_prosphora_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gestionnaire', 'Gestionnaire'), ('pasteur', 'Pasteur'), ('comptable', 'Comptable'), ('caissier', 'Caissier')], max_length=20),
        ),
    ]
