# Generated by Django 4.2.16 on 2025-10-23 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api_prosphora_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahadi',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='payement_offrande',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='prevoir',
            name='annee_prevus',
        ),
        migrations.AddField(
            model_name='prevoir',
            name='date_prevus',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sorte_offrande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
