# Generated by Django 4.2.16 on 2026-01-05 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api_prosphora_App', '0002_ahadi_user_etatbesoin_user_groupe_previsions_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarante_Pourcent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_offrande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_prosphora_App.sorte_offrande')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
