# Generated by Django 4.2.16 on 2026-06-06 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api_prosphora_App', '0003_quarante_pourcent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchangeMonaie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tauxechange', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
